name: avantri_test
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  http: ^0.13.5
  http_parser: ^4.0.2
  cupertino_icons: ^1.0.2
  email_validator: ^2.1.17
  connectivity_plus: ^3.0.2
  shared_preferences: ^2.0.17

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
